import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/redux-saga/provider'
import Navbar from '@/ui/navbar'
import Sidebar from '@/ui/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Navbar/>
          <div className='grid xl:grid-cols-6 min-h-screen'>
            <div className='col-span-1'><Sidebar/></div>
            <div className='xl:col-span-5'><Providers>{children}</Providers></div>
          </div>
      </body>
    </html>
  )
}
