export const USER_SIGNUP_REQ = 'USER_SIGNUP_REQ'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const GET_ALL_USER_REQ = 'GET_ALL_USER_REQ'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const GET_ONE_USER_REQ = 'GET_ONE_USER_REQ'
export const GET_ONE_USER_SUCCESS = 'GET_ONE_USER_SUCCESS'
export const GET_ONE_USER_FAIL = 'GET_ONE_USER_FAIL'

export const EMPLOYEE_SIGNUP_REQ = 'EMPLOYEE_SIGNUP_REQ'
export const EMPLOYEE_SIGNUP_SUCCESS = 'EMPLOYEE_SIGNUP_SUCCESS'
export const EMPLOYEE_SIGNUP_FAIL = 'EMPLOYEE_SIGNUP_FAIL'

export const GET_ALL_EMPLOYEE_REQ = 'GET_ALL_EMPLOYEE_REQ'
export const GET_ALL_EMPLOYEE_SUCCESS = 'GET_ALL_EMPLOYEE_SUCCESS'
export const GET_ALL_EMPLOYEE_FAIL = 'GET_ALL_EMPLOYEE_FAIL'

export const USER_LOGIN_REQ = 'USER_LOGIN_REQ';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';


export const USER_LOGOUT = 'USER_LOGOUT';