import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/redux-saga/provider'
import Navbar from '@/app/ui/navbar'
import Sidebar from '@/app/ui/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className='bg-gray-100'>
        <div className='flex flex-col gap-3'>
          <div className='flex-none'>
            <Navbar/>
          </div>
          <div className='flex flex-1'>
            <div className='min-h-full flex-none'>
              <Sidebar/>
            </div>
            <div className='min-h-full md:px-3 flex-1'>
              <Providers>{children}</Providers>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
